apiVersion: v1
kind: Service
metadata:
  name: appuser-poc-service
  labels:
    app: appuser-poc
spec:
  type: ClusterIP
  selector:
    app: appuser-poc
  ports:
    - name: metrics-port
      protocol: TCP
      port: 8080
      targetPort: 8080